name: Python Tests

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11.0
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.0'
    - name: Run tests
      run: |
        python3 -m unittest discover -s intelligest_smart_home/tests -p '*_tests.py'

